### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by jamesgoodhouse** [ns1-terraform/terraform-provider-ns1#117]
### Terraform Version
0.12.21

### Affected Resource(s)
Likely all, but the one we're having problems with is `ns1_user`.

### Expected Behavior
A successful run, regardless of the number of resources.

### Actual Behavior
Receiving `429 Rate limit exceeded` errors when doing runs with large number of resources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have hundreds of NS1 user resources managed by Terraform
1. run `tf refresh` and wait for `429 Rate limit exceeded` errors

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- previously closed similar issue (https://github.com/ns1/ns1-go/issues/99)
- ns1-go library (https://github.com/terraform-providers/terraform-provider-ns1/issues/2)

**Comment by mccarthy-james** [comment]
Hi @jamesgoodhouse. We have updated our provider documentation with advice on how to avoid 429 errors: https://www.terraform.io/docs/providers/ns1/index.html#ns1_rate_limit_parallelism -- hopefully this will prove effective for you.

**Comment by pcatalini** [comment]
@jamesgoodhouse does the documentation make sense? can we consider this issue close?

**Comment by eravin-ns1** [comment]
Closing - please open a new issue if the workaround described at https://registry.terraform.io/providers/ns1-terraform/ns1/latest/docs#rate_limit_parallelism is nor sufficient.
