### ISSUE TITLE
How to manage "records_allow" list of specific records to which the API key is allowed access?

### ISSUE THREAD

**Issue by pulchart** [ns1-terraform/terraform-provider-ns1#153]
### Terraform Version

all

### Affected Resource(s)
ns1_apikey

### Terraform Configuration Files
n/a

### Debug Output
n/a
### Panic Output
n/a
### Expected Behavior

ns1 provider can manage "records_allow" object of API key (and other resources)

### Actual Behavior

Cannot configure and manage list allowed records of API key.

### Steps to Reproduce

n/a

### Important Factoids

n/a

### References

n/a

**Comment by pcatalini** [comment]
@pulchart hey, we already implement this 
https://github.com/ns1-terraform/terraform-provider-ns1/pull/165
but we add documentation just for the ns1_team resource
I created a ticket in our backlog to update the documentation, however, you can follow the following documentation which will be the same for the api_key resource
https://registry.terraform.io/providers/ns1-terraform/ns1/latest/docs/resources/team
basically, you can pass n objects for dns_records_allow or  dns_records_deny as shown bellow

`    dns_records_allow {
      domain = "a.pcatalini.com"
      include_subdomains = false
      zone = "pcatalini.com"
      type = "A"
  }
    dns_records_allow {
      domain = "my.ns1.com"
      include_subdomains = true
      zone = "ns1.com"
      type = "A"
  }
    dns_records_deny {
      domain = "gannett_test.com"
      include_subdomains = false
      zone = "gannett_test.com"
      type = "A"
   }`

**Comment by eravin-ns1** [comment]
Provider docs will be corrected in upcoming release 1.13.2, closing.
