### ISSUE TITLE
Support import of ns1_user and ns1_team resources

### ISSUE THREAD

**Issue by ricbartm** [ns1-terraform/terraform-provider-ns1#162]
### Terraform Version
Terraform 0.12.8
ns1 provider 1.9.4

### Affected Resource(s)
- ns1_user
- ns1_team

### Terraform Configuration Files
```
resource "ns1_user" "user" {
  provider                   = "ns1"
  name                       = "test"
  username                   = "custom_user_prefix_test"
  email                      = "test@domain.com"
  teams                      = ["team-hash"]

  notify = {
    billing = false
  }

  # Because users can change their own name, we ignore changes to avoid unexpected drifts
  lifecycle {
    ignore_changes = ["name"]
  }
}
```

### Debug Output
```
$ terraform import 'ns1_user.user' mytestuser
Acquiring state lock. This may take a few moments...
ns1_user.user: Importing from ID "mytestuser"...

Error: resource ns1_user doesn't support import
```

### Panic Output
Does not apply

### Expected Behavior
Provider should support importing users and teams

### Actual Behavior
Provider does not support importing users and teams

### Steps to Reproduce
1. Use provided configuration file
2. run `terraform import 'ns1_user.user' mytestuser`

### Important Factoids
We have been told that when a user is deleted, the user is put on a deletion queue for 7 days. During this period, the username is reserved (as in-use), but not visible through the NS1 users API or the UI. Apparently, an NS1 support representative could recover the account from the deletion queue in case of accidental user deletion.

Nevertheless, nothing of this is useful under the following scenarios:
* We delete a user, and we try to recreate it again. The username is in the deletion queue and API answers that `user already exists` 
* If we reach out to support for them to recover the username, it stays in the limbo, outside of our automation IaC strategy

These problems would go away if the provider would allow importing team and users. I guess it's a common scenario for folks that:
* Don't use SAML integration
* started with manual user creation
* want to import the users into terraform IaC

### References
N/A

**Comment by dabo-ZON** [comment]
Would be very helpful, and is a common use case.

**Comment by ThiagoYU** [comment]
Hi @ricbartm, thank you for reporting this.
We already added this to our backlog.

**Comment by norman-zon** [comment]
This would be very useful.

**Comment by ricbartm** [comment]
Apparently version [1.11.2](https://github.com/ns1-terraform/terraform-provider-ns1/blob/master/CHANGELOG.md#1122-january-07-2022) implements the [ability to import these resources](https://github.com/ns1-terraform/terraform-provider-ns1/pull/193). I won't have time to test this in the sort term, so leaving the comment here in order interested folks to be notified. I'll also close the issue because it's theoretically implemented.
