### ISSUE TITLE
Support Darwin Arm64 (apple silicon, Mac M1 chip)

### ISSUE THREAD

**Issue by samjewell** [ns1-terraform/terraform-provider-ns1#169]
Running `terraform init` with this provider present:

```
terraform {
  required_providers {
    ns1 = {
      source = "ns1-terraform/ns1"
    }
  }
}

…etc…
```

I get this output, on an apple M1 mac:

```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/ns1-terraform/ns1 v1.11.0 does not have a package available for your current
│ platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
│ Other versions of this provider may have different platforms supported.
```

I can confirm on the Releases page here: https://github.com/ns1-terraform/terraform-provider-ns1/releases that you haven't built an asset for Darwin Arm64 yet. Please can you do this 🙏

**Comment by pcatalini** [comment]
@samjewell  Thank you for reporting this issue.
We already added this to our backlog.

**Comment by antoine-habran** [comment]
Hello,


Do you have any news about building a darwin_arm64 version? I'm facing this issue too and will be mandatory for us to use NS1 services :(


Thx

**Comment by Zach-Johnson** [comment]
This is updated on v1.12.5 now
