### ISSUE TITLE
Changing filters order in a record fails (when filters have different config options)

### ISSUE THREAD

**Issue by shmulika** [ns1-terraform/terraform-provider-ns1#174]
Hi there,

### Terraform Version
Terraform v1.0.6

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    ns1 = {
      source  = "ns1-terraform/ns1"
      version = "= 1.11.0"
    }
  }
}

provider "ns1" {
  apikey = "***********"
}

resource "ns1_zone" "routing" {
  zone = "ns1routingtest.mydomain"
  ttl = 600
}

resource "ns1_record" "edge" {
  zone   = "${ns1_zone.routing.zone}"
  domain = "edge.${ns1_zone.routing.zone}"
  type   = "A"
  ttl    = 60

  regions {
    name = "east"
    meta = {
      georegion = "US-EAST"
    }
  }

  regions {
    name = "usa"
    meta = {
      country = "US"
    }
  }

  answers {
    answer  = "1.1.1.1"
    region  = "east"
  }

  answers {
    answer = "2.2.2.2"
    region = "usa"
  }
    
  filters {
    filter = "select_first_n"
    config = {
      N = 1
    }
  }

  filters {
    filter = "geofence_country"
  }  

}
```

### Debug Output
https://gist.github.com/shmulika/80121d8b9a7ec6bc918c054156e90cfb

### Expected Behavior
When I change the order of the filters in the HCL (swap selec_first_n with geofence_country), I expect the order to change in NS1 platform

### Actual Behavior
Seems like Terraform is trying to apply the new filter configuration on the filters according to the order they were before. e.g. it would say that "N=1" is not a valid configuration (I assume because geofence_country filter doesn't have config field 'N')

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create an HCL like mine and apply it
2. reverse the order of the filter
3. `terraform apply` again, the problem will occur

**Comment by ThiagoYU** [comment]
@Zach-Johnson This issue was merged and I think it'll be included in the next release, can we close this?

**Comment by Zach-Johnson** [comment]
@ThiagoYU yep, thanks for the heads up! I will close this.
