### ISSUE TITLE
Support for "override_ttl" on ALIAS records

### ISSUE THREAD

**Issue by ricbartm** [ns1-terraform/terraform-provider-ns1#203]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.0.11

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record

### Terraform Configuration Files
```hcl
resource "ns1_record" "record" {
  zone              = data.ns1_zone.dns_zone.zone
  domain            = "${var.public_subdomain}.subdomain.${data.ns1_zone.dns_zone.zone}"
  type              = "ALIAS"
  ttl               = 30
  use_client_subnet = true

  answers {
    answer = var.old _dns_record
    meta = {
      weight = "100"
      note   = "gcp"
    }
  }

  answers {
    answer = var.new_dns_record
    meta = {
      weight = "0"
      note   = "aws"
    }
  }

  filters {
    filter = "weighted_sticky"
  }

  filters {
    filter = "select_first_n"

    config = {
      N = 1
    }
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
We have a way to enable the "Override TTL" toggle we have in the UI
![image](https://user-images.githubusercontent.com/4131130/151361972-152b61b1-8217-451b-ad7d-0160b6344e3c.png)

### Actual Behavior
TTL is set at the DNS record level, but not honoured (toggle disabled)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by mccarthy-james** [comment]
Hi Ricardo, the option to do this may have been added since you opened the ticket, but recent versions of the provider at least you can add `override_ttl = "true"` to the alias record's configuration.

**Comment by eravin-ns1** [comment]
Closing, requested feature is currently supported.
