### ISSUE TITLE
`ns1_monitoringjob` does not persist `tls_add_verify` in the Terraform statefile

### ISSUE THREAD

**Issue by zahiar** [ns1-terraform/terraform-provider-ns1#219]
### Terraform Version
`1.1.9`

### Affected Resource(s)
- ns1_monitoringjob

### Example Code
```
resource "ns1_monitoringjob" "regional-monitor" {
...

  config = {
    tls_add_verify  = false
    connect_timeout = 5
    idle_timeout    = 3
    method          = "GET"
    url             = "https://somewebsite/healthcheck"
  }
}
```

### Expected Behavior
The statefile should store the full config as defined in the `ns1_monitoringjob` resource above.

### Actual Behavior
The `tls_add_verify` key in the `config` block is not stored in the statefile. Therefore subsequent Terraform plans will always show that `tls_add_verify` needs adding, even though the change has already been applied prior but is not persisted in the Terraform statefile.

Sample from the Terraform statefile
```
{
      "module": "module.geo-lb",
      "mode": "managed",
      "type": "ns1_monitoringjob",
      "name": "regional-monitor",
      "provider": "provider[\"registry.terraform.io/ns1-terraform/ns1\"]",
      "instances": [
        {
          "index_key": "ap-northeast-1",
          "schema_version": 0,
          "attributes": {
            "active": true,
            "config": {
              "connect_timeout": "5",
              "idle_timeout": "3",
              "method": "GET",
              "url": "https://somewebsite/healthcheck"
            },
...
```

**Comment by zahiar** [comment]
Further debugging, only applies to `tls_add_verify  = false`, if `tls_add_verify  = true`, that is persisted to the statefile.

**Comment by zahiar** [comment]
The issue lies with the API, if the `tls_add_verify` is set to `true` on the monitoring job, then the API will return that in its JSON response, otherwise it will be omitted.

Can be reproduced by creating a single monitoring job and then making a request to the API to get the monitoring job details (`curl -X GET -H "X-NSONE-Key: ???" https://api.nsone.net/v1/monitoring/jobs`):

With the `tls_add_verify` set to `true`
```
...
    "config": {
      "ssl": true,
      "host": "example-elb-uswest.aws.amazon.com",
      "port": 443,
      "send": "HEAD / HTTP/1.0\r\n\r\n",
      "tls_add_verify": true
    },
...
```

With the `tls_add_verify` set to `false`
```
...
    "config": {
      "ssl": true,
      "host": "example-elb-uswest.aws.amazon.com",
      "port": 443,
      "send": "HEAD / HTTP/1.0\r\n\r\n"
    },
...
```

Ideally the API's response should return all fields for consistency.

**Comment by wsomervell** [comment]
@zahiar with a recent API fix, this issue should be resolved. could you please confirm?

**Comment by zahiar** [comment]
@wsomervell I re-ran a plan and can confirm it works now 👍
