### ISSUE TITLE
ns1_monitoringjob regions are unordered and nondeterministic

### ISSUE THREAD

**Issue by frankyi-gh** [ns1-terraform/terraform-provider-ns1#223]
Hi, I'm seeing a similar issue to #19, but on the `ns1_monitoringjob` resource

### Terraform Version
```
# terraform -v
Terraform v0.15.5
on darwin_amd64
```

### Affected Resource(s)
- ns1_monitoringjob

### Terraform Configuration Files
```hcl
resource "ns1_monitoringjob" "monitor" {
  name   = "my-monitor"
  active = true
  mute   = false

  job_type      = "http"
  regions       = ["lga", "dal", "sjc"]
  frequency     = 60
  rapid_recheck = true
  policy        = "quorum"

  config = {
    url    = var.url
    method = var.method
    connect_timeout = 5
    idle_timeout    = 3
    user_agent      = "NS1 HTTP Monitoring Job"
  }

  rules {
    key        = "status_code"
    comparison = "<="
    value      = "399"
  }

  notify_delay    = 1
  notify_repeat   = 60
  notify_failback = true
  notify_regional = true
  notify_list     = ns1_notifylist.monitor.id
}
```

### Expected Behavior
After applying, subsequent plans should show no changes.

### Actual Behavior
Similar to #19, after applying, plans continue to show a diff because the order of the `regions` is different. Applying subsequent plans doesn't fix the problem.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a monitoring job with multiple regions
2. `terraform apply`
3. sometimes (non deterministic?), the ordering is different and `terraform plan` will show changes to the `regions`
4. Running `terraform apply` again does nothing - plans still show a diff

### References
Similar issue to #19

**Comment by mccarthy-james** [comment]
I can reproduce this issue. A workaround, that at least works for me, is to place the regions in reverse alphabetical order. So `regions       = ["sjc", "lga", "dal"]` for your configuration. This makes the plan show 'No changes'.

**Comment by agimenez** [comment]
@mccarthy-james that doesn't work for me, I get the bogus plan all the time no matter how I sort the regions. @frankyi-gh does it work for you?

**Comment by mccarthy-james** [comment]
@agimenez Unfortunately after I wrote this I realised I was wrong. In fact each monitor expects it's regions to be in a certain way. So if your Terraform output states:

```      ~ regions         = [
          - "gru",
          - "nrt",
          - "sjc",
          - "ams",
          - "syd",
          - "lhr",
            "dal",
          + "lhr",
          + "syd",
          + "ams",
          + "sjc",
          + "nrt",
          + "gru",
        ]```

The order it expects is where the minus symbols are (or no symbols) and not where the the plus symbols are. So for the above the configuration should be:

This is certainly a bug, but this seems to to be a workaround (at least for single monitors).

**Comment by mccarthy-james** [comment]
v1.12.8 fixes this issue once you rearrange the regions alphabetically in your config. Make sure you have the latest version of Terraform as well (it didn't work for me with an older one).

**Comment by eravin-ns1** [comment]
We've adjusted this code in v1.13.0 - "terraform apply" should now behave as expected without regard to whether the regions are sorted in your resource file.
