### ISSUE TITLE
account_manage_plan shows deprecation on team

### ISSUE THREAD

**Issue by brianeclow** [ns1-terraform/terraform-provider-ns1#228]
### Terraform Version
`0.13.7`

### Affected Resource(s)

- ns1_team

### Terraform Configuration Files

```hcl
resource "ns1_team" "administrative" {
  name = "Administrative Team"

  account_manage_plan            = true
}
```

```hcl
resource "ns1_user" "admin_user" {
  name     = "Admin User"
  username = "adminusercompany"
  email    = "adminuser+nsone@company.com"
  teams = [
    ns1_team.administrative.id
  ]
}
```

### Debug Output

```text
Warning: "account_manage_plan": [DEPRECATED] obsolete, should no longer be used

  on team_administrative.tf line 1, in resource "ns1_team" "administrative":
   1: resource "ns1_team" "administrative" {
```

### Panic Output
none

### Expected Behavior

The option should be set without incident, as the particular deprecation was on the user level, not the team level. At least, according to the API guides, when I looked about 6 months ago.

### Actual Behavior

The option is set with warning.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The API guides do not indicate this is deprecated.

### References

Can't directly link to the "create team" API end point, but the value is still listed as being accessible (and not deprecated)
https://ns1.com/api -> Account -> Team -> Create

**Comment by eravin-ns1** [comment]
This endpoint is fully deprecated. Documentation will be fixed in 1.13.2 with above PR.
