### ISSUE TITLE
CAA records cannot have a space after domain

### ISSUE THREAD

**Issue by sebmck** [ns1-terraform/terraform-provider-ns1#238]
Record answer values are split on spaces, but CAA records should only allow three elements to allow for additional metadata.

ie. the answer value `"0 issue digicert.com; account=xyz"` will result in a NS1 API error as `["0", "issue digicert.com;", "account=xyz"]` is not valid. It should be `["0", "issue digicert.com; account=xyz"]` (note: the last element).

### Terraform Version

v1.2.8

### Affected Resource(s)

- ns1_record

### Expected Behavior
What should have happened?

Record should have been created.

### Actual Behavior
What actually happened?

An error:

```
 Error: PUT https://api.nsone.net/v1/zones/<ZONE>/<ZONE>/CAA: 400 "[0, issue, digicert.com;, account=xyz]" is invalid for "CAA" record type 
```

### Steps to Reproduce

Create a CAA record additional metadata after the domain. eg.

```
resource "ns1_record" "caa" {
  type   = "CAA"
  zone   = var.domain
  domain = var.domain

  answers {
    answer = "0 issue digicert.com; account=xyz"
  }
}
```

**Comment by eravin-ns1** [comment]
Thank you for the bug report! This is fixed in release 1.13.2-pre4.
