### ISSUE TITLE
Linked records are force-recreated when "link" argument is modified

### ISSUE THREAD

**Issue by ricbartm** [ns1-terraform/terraform-provider-ns1#239]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
terraform -v
Terraform v0.12.31
+ provider.ns1 v1.13.0
``

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
locals {
   default-dns-record-ttl = "900"
   records_linked = {
      a_records = {
         "www.${data.ns1_zone.dns_zone.zone}"  = "target.domain.com",
      }
   }
}

resource "ns1_record" "a_records" {
  for_each = local.records_linked.a_records

  zone   = data.ns1_zone.dns_zone.zone
  domain = each.key
  type   = "A"
  ttl    = lookup(each.value, "ttl", local.default-dns-record-ttl)

  dynamic "answers" {
    iterator = entry
    for_each = each.value.answers

    content {
      answer = entry.value
    }
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
No panic

### Expected Behavior
My expectation is that the `ns1_record` gets a modification in place. 

### Actual Behavior
The `ns1_record` forces replacement when the `link` argument of the resource is modified.

Because the way Terraform treats resource replacements, I'm pretty sure the operation won't be atomic, and there would be a time while the DNS record won't exist and will return a `NXDOMAIN` causing an outage for us.

I have seen in the code that the `link` argument is expected to [recreate the resource](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors) because is defined as `ForceNew: true`. See [here](https://github.com/ns1-terraform/terraform-provider-ns1/blob/9600353e55329de4e2bb3bc5fa9a128b0e963e19/ns1/resource_record.go#L82-L85)

For reference, in the NS1 Connect UI this change can be done without any problem. When the linked record is created for the first time, a PUT request with the following payload is sent to the API.

When the linked record is modified, a POST request is sent with the following contents:
```json
{
  "displayName":"dns_zone.com",
  "IDNDomain":"testrecord.dns_zone.com",
  "IDNName":"dns_zone.com",
  "IDNZone":"dns_zone.com",
  "customer":3837,
  "domain":"testrecord.dns_zone.com",
  "zone":"dns_zone.com",
  "updated_at":1668079816,
  "created_at":1668079816,
  "use_client_subnet":true,
  "id":"636ce0c83686c40081abe602",
  "regions":{},
  "meta":{},
  "ttl":3600,
  "tier":1,
  "zone_name":"dns_zone.com",
  "type":"CNAME",
  "answers":[
    {
      "answer":[
        "targetdnsrecord.dns_zone.com"
      ],
      "id":"636ce0c83686c400889647df"
    }
  ],
  "networks":[0,42]
}
```

So I don't know if this is a justified limitation of the NS1 provider, or something that has can be solves easily.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a linked record pointing to a existing DNS record
2. Introduce a change in the `link` argument is modified
3. `terraform plan`

Observe how the plan tries to recreate the resource

### Important Factoids
Nothing

### References
Nothing

**Comment by eravin-ns1** [comment]
This should be fixed in pre-release `1.13.1-pre1`. You'll need to specify the version explicitly to use it:
```
  required_providers {
    ns1 = {
      source = "ns1-terraform/ns1"
      version = "1.13.1-pre1"
    }
  }
```

**Comment by ricbartm** [comment]
Hello folks. I confirm the prerelease does a in-place modification of the `ns1_record` resource 🙌 . I'm not familiarised with the release cadence of the provider. When shall we expect this 1.13.1 version to be released?

**Comment by eravin-ns1** [comment]
Thanks for the confirmation!

Regarding the release cadence, we don't have an official schedule. Note that 1.13.1-pre1 is still a supported release. Is there a reason that you don't want to hard-code the version string in your resource file?

**Comment by ricbartm** [comment]
We are actually hard-pining the version in our Terraform code, so that is not a problem for us.

I just assumed that the pre-release may be released from a feature branch that may or may not contain changes that were not in master/main branch yet and not properly tested or so.

From my side this issue can be closed 👍
