### ISSUE TITLE
Add data source for Monitoring Regions

### ISSUE THREAD

**Issue by montmanu** [ns1-terraform/terraform-provider-ns1#283]
It would be helpful if there was a data source that returned the [list of all available monitoring regions](https://ns1.com/api?docId=2247), including display name for the region, the region code to use when provisioning, and the list of all subnets from which monitoring traffic is generated in each region. The result could then be used to identify network traffic generated by NS1's monitoring services (e.g., for configuring firewall rules, generating access log queries, etc).

Here are a few examples of similar data sources offered by other providers:
- [`aws_ip_ranges`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ip_ranges)
- [`google_monitoring_uptime_check_ips`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/monitoring_uptime_check_ips)
- [`google_netblock_ip_ranges`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/netblock_ip_ranges)
- [`datadog_ip_ranges`](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/ip_ranges)
- [`fastly_ip_ranges`](https://registry.terraform.io/providers/fastly/fastly/latest/docs/data-sources/ip_ranges)

See ["NS1's monitoring regions and IPs"](https://help.ns1.com/hc/en-us/articles/360058003733-NS1-s-monitoring-regions-and-IPs) for more details.

**Comment by pburrows-ns1** [comment]
Hi @montmanu 
We have added a datasource now which is available with version `2.2.0`
https://registry.terraform.io/providers/ns1-terraform/ns1/latest/docs/data-sources/monitoring_regions

Thanks
Paul

**Comment by montmanu** [comment]
Thank you!
