### ISSUE TITLE
Feature Request - resource for "GLOBAL IP ALLOW LISTS"

### ISSUE THREAD

**Issue by packet-blaster** [ns1-terraform/terraform-provider-ns1#284]
I have a "GLOBAL IP ALLOW LISTS" resource in NS1 that doesn't seem to be available in terraform. Can we get this resource added?

The option is in Settings -> Security Settings -> GLOBAL IP ALLOW LISTS

Thank you,
PacketBlaster

**Comment by pburrows-ns1** [comment]
Hello @packet-blaster 

This is now available as of version v2.0.6
