### ISSUE TITLE
Add support for resource tags

### ISSUE THREAD

**Issue by dzierzanowski** [ns1-terraform/terraform-provider-ns1#286]
Hello, this is a feature request to add support for record tags, as they are described in the [API documentation](https://ns1.com/api?docId=2185#apidoc-418288).

### Terraform Version
```
1.4.4
```

### Affected Resource(s)
- `ns1_record`

### Terraform Configuration Files
```hcl
resource "ns1_record" "www" {
  zone   = ns1_zone.tld.zone
  domain = "www.${ns1_zone.tld.zone}"
  type   = "CNAME"

  tags   = {
    example_key = "example value"
  }
}
```

### Debug Output
\-

### Panic Output
\-

### Expected Behavior
CNAME record created with `{ example_key = "example value }` tag set.

### Actual Behavior
\-

### Steps to Reproduce
\-

### Important Factoids
\-

### References
\-

**Comment by ponbiki** [comment]
Tag/Blocked_Tag support added for managed DNS implementation in v2.0.10
