### ISSUE TITLE
Can't pull provider from registry due to checksums

### ISSUE THREAD

**Issue by Tigershark2005** [ns1-terraform/terraform-provider-ns1#287]
### Terraform Version
v1.4.5

### Affected Resource(s)
- all
### Terraform Configuration Files
This is an issue with the provider, not the code.

### Debug Output
"terraform init" failed when using 2.0.2 a few weeks ago so I've been using 2.0.0. Now I'm getting issues with 2.0.0 and init fails on all the versions I've tried so far.

Error while installing ns1-terraform/ns1 v2.0.0: could not query provider registry for registry.terraform.io/ns1-terraform/ns1: failed to retrieve authentication checksums for provider: 403 Forbidden returned from objects.githubusercontent.com

### Expected Behavior
init pulls the provider successfully

### Actual Behavior
Error shown above

### Steps to Reproduce
run terraform init with the required providers block
```
  required_providers {
    ns1 = {
      source  = "ns1-terraform/ns1"
      version = "2.0.0"
    }
  }
```

### Important Factoids
Running through Terraform Cloud for state but I manually downloaded the 2.0.2 provider to see if that was a valid workaround. Haven't gotten that to work.

**Comment by jfarrell-NS1** [comment]
hi Tigershark2005, I wasn't able to reproduce this issue, its possible it was a temporary issue with Hashicorps servers as it looks like they were recently doing maintenance. Are you still having issues?

**Comment by Tigershark2005** [comment]
Yes, still having the issue. Looking into things on my end but haven't come across anything useful yet.

**Comment by Tigershark2005** [comment]
No proxy is being used. Not sure what has to be validated with checksums whether that's within Terraform or some cert or what.

**Comment by jfarrell-NS1** [comment]
Yes this is hard for me to debug without being able to reproduce, can you try deleting your terraform plugin cache if you have one `~/.terraform.d/plugins/registry.terraform.io/ns1-terraform/ns1` deleting 2.0.0

**Comment by Tigershark2005** [comment]
No cache at this point. It's a cloud state so I usually don't have any local providers.

**Comment by jfarrell-NS1** [comment]
The issue you are having sounds like [this one](https://support.hashicorp.com/hc/en-us/articles/1500001362182-Failed-to-install-provider-after-upgrading-to-Terraform-0-14) if you delete your lock file it should resolve the problem.
