### ISSUE TITLE
v2.0.9 of the Provider is a breaking change / not backwards compatible

### ISSUE THREAD

**Issue by tlkamp** [ns1-terraform/terraform-provider-ns1#304]
### Terraform Version
Terraform v1.5.2

### Affected Resource(s)
`ns1_record`

### Terraform Configuration
```hcl
resource "ns1_record" "dns" {
  zone   = var.domain_name
  domain = "${var.record}.${var.domain_name}"
  type   = "A"
  ttl    = var.records_ttl

  dynamic "answers" {
    for_each = toset(var.ips)
    content {
      answer = answers.value
    }
  }
}
```

### Plan Output
```
  # module.indexer.ns1_record.dns will be updated in-place
  ~ resource "ns1_record" "dns" {
        id                = "[redacted]"
        # (7 unchanged attributes hidden)

      + answers {
          + answer = "[redacted]"
        }

        # (3 unchanged blocks hidden)
    }
```

### Expected Behavior
I expected updates to the answer section on my record to succeed.

### Actual Behavior
I'm receiving the following error:
`Error: POST https://api.nsone.net/v1/zones/MYZONE/MYRECORD/A: 400 tags and blocked_tags must be updated together`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create DNS resources with no `tags` or `blocked_tags` specified
2. Trigger an update to the record

### Workaround
- Pin the version to `v2.0.8`
- Specify values for `tags` and `blocked_tags`
  - Specifying `null` or empty values (`{}` and `[]` respectively) does not work 

### References
- This does not occur in version v2.0.8
- I noticed no acceptance tests were run when the merge completed, which probably would have revealed the issue.
- I suspect it is related to the upstream ns1-go client update.

**Comment by tlkamp** [comment]
I was able to showcase the `omitempty` the behavior using Go Playground: https://go.dev/play/p/RyfVZ2Mubwd 

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"encoding/json"
	"fmt"
)

type OmitEmpties struct {
	Map    map[string]string `json:"map,omitempty"`
	List   []string          `json:"list,omitempty"`
	Number int               `json:"number"`
}

type NoOmits struct {
	Map    map[string]string `json:"map"`
	List   []string          `json:"list"`
	Number int               `json:"number"`
}

func main() {

	noOmits := &NoOmits{
		Number: 1,
	}

	omits := &OmitEmpties{
		Number: 1,
	}

	fmt.Println("OmitEmpty")
	omitBytes, err := json.Marshal(omits)
	fmt.Println(err)
	fmt.Println(string(omitBytes))

	fmt.Println()
	fmt.Println()

	fmt.Println("No Omit Empty")
	noOmitBytes, err := json.Marshal(noOmits)
	fmt.Println(err)
	fmt.Println(string(noOmitBytes))
}
```

Note the output:
```console
OmitEmpty
<nil>
{"number":1}


No Omit Empty
<nil>
{"map":null,"list":null,"number":1}
```

**Comment by tlkamp** [comment]
Related PRs:
- Blocked Tags: https://github.com/ns1/ns1-go/pull/220/files
- Release of Blocked Tags: https://github.com/ns1/ns1-go/pull/221
- Tags: https://github.com/ns1/ns1-go/pull/222 (not yet merged but will cause similar issues)

**Comment by pburrows-ns1** [comment]
Closed based on discussion in https://github.com/ns1/ns1-go/pull/222

@tlkamp Please open a new issue if you're still experiencing any with the latest provider version.
