### ISSUE TITLE
Unable to create ns1_redirect resource when target url contains query string parameters

### ISSUE THREAD

**Issue by AlejandroTrev** [ns1-terraform/terraform-provider-ns1#326]
Hi there,

Using the `ns1_redirect` resource that was introduced in #307 (released in v.2.3.0), I'm unable to create a redirect where the target url contains query string parameters.

### Terraform Version
```
terraform -v
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/ns1-terraform/ns1 v2.4.0
```

### Affected Resource(s)
- ns1_redirect

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    ns1 = {
      source  = "ns1-terraform/ns1"
      version = "~> 2.4.0"
    }
  }
}

provider "ns1" {
  apikey = "YOUR_API_KEY_HERE"
}

resource "ns1_redirect" "foo_testingzone_com_redirect" {
  domain           = "foo.testingzone.com"
  path             = "/"
  target           = "https://www.google.com/?foo=bar"
  forwarding_mode  = "none"
  forwarding_type  = "permanent"
  query_forwarding = false
}

```

### Expected Behavior
The plan should indicate that the redirect will be created.

### Actual Behavior

An error message is returned:
```
│ Error: target is not a valid FQDN, got: https://www.google.com/?foo=bar
│
│   with ns1_redirect.foo_testingzone_com_redirect,
│   on main.tf line 22, in resource "ns1_redirect" "foo_testingzone_com_redirect":
│   22:   target           = "https://www.google.com/?foo=bar"
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
The `target` field uses the ValidateFunc `validateURL` defined here: https://github.com/ns1-terraform/terraform-provider-ns1/blob/master/ns1/resource_redirect.go#L373

The regex should be updated to allow query string parameters in the url. NS1 supports target urls with query string parameters when creating the redirects through their admin console. Example:

![redirects](https://github.com/user-attachments/assets/42dbd325-162f-41ce-bedd-c5b5369be6aa)

**Comment by AlejandroTrev** [comment]
@fformica just a heads up about this one, since you worked on #307

**Comment by fformica** [comment]
Hi @AlejandroTrev, thanks for the heads-up!
We need to improve this regex: https://github.com/ns1-terraform/terraform-provider-ns1/blob/b06bab5812db84a2933649e507f85e5ae1a4b079/ns1/resource_redirect.go#L373
However I also tried creating a redirect with that target and when I curl to it I see
```
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< location: https://www.google.com/
```
So it looks like the query part is currently ineffective: we'll have to do an investigation server side as well.
