### ISSUE TITLE
Interface conversion error when specifying more than one country on a region

### ISSUE THREAD

**Issue by glennslaven** [ns1-terraform/terraform-provider-ns1#37]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.8

### Affected Resource(s)
- ns1_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "ns1_record" "endpointgroup" {
  zone              = "example.com"
  domain          = "record.example.com"
  type              = "A"

  ttl               = 300
  use_client_subnet = true

  answers = [
    {
      answer = "192.0.2.2"
      region = "SYD"

      meta = {
        up = true
      }
    },
    {
      answer = "192.0.2.1"
      region = "SYD"

      meta = {
        up = true
      }
    },
  ]

  regions = [
    {
      name = "SYD"
      meta = {
        up      = true
        country = "WF,WS,FJ,FM,PW,TV,NC,NF,TO,NZ,PF,TK,NR,PN,NU,PG,CK,GU,AS,AU,VU,KI,MH,MP,SB"
      }
    },
  ]

  filters {
    filter = "up"
  }

  filters {
    filter = "geotarget_country"
  }

  filters {
    filter = "select_first_n"
    config = {N=2}
  }
}
```

### Debug Output
https://gist.github.com/glennslaven/9cf7721f9f608a9da5fcdf9e9c06b8b6

### Expected Behavior
Create the record with the correct country meta values set

### Actual Behavior
Crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by impicklejon** [comment]
Trying to add multiple georegion labels causes the same crash.
After the crash terraform state has no ns1_record for the zone created.
This causes the record to be unmanageable through terraform as any change will try to recreate the record and fail because it already exists in ns1.

**Comment by ThiagoYU** [comment]
Hi @glennslaven, thank you for reporting this.
We already added this to our backlog.

**Comment by eravin-ns1** [comment]
Looks like we fixed this a while ago but forgot to update this issue. I used the file below to try to reproduce and everything worked as expected. Note the updated block syntax and cross-reference between the zone and the record.

```
resource "ns1_zone" "junk99" {
  zone = "junk99-test-zone.io"
}

resource "ns1_record" "endpointgroup" {
  zone              = ns1_zone.junk99.zone
  domain          = "record.${ns1_zone.junk99.zone}"
  type              = "A"

  ttl               = 300
  use_client_subnet = true

  answers {
      answer = "192.0.2.2"
      region = "SYD"

      meta = {
        up = true
      }
    }

  answers {
      answer = "192.0.2.1"
      region = "SYD"

      meta = {
        up = true
      }
    }

  regions {
      name = "SYD"
      meta = {
        up      = true
        country = "WF,WS,FJ,FM,PW,TV,NC,NF,TO,NZ,PF,TK,NR,PN,NU,PG,CK,GU,AS,AU,VU,KI,MH,MP,SB"
      }
    }

  filters {
    filter = "up"
  }

  filters {
    filter = "geotarget_country"
  }

  filters {
    filter = "select_first_n"
    config = {N=2}
  }
}
```
